### ISSUE TITLE
Bitvector projection is wrong

### ISSUE THREAD

**Issue by maurer** [maurer/libbap#2]
The function `bap_bitvector_contents` is returning incorrect values. I believe this is because Bap's `Bitvector.enum_chars` is buggy, and am looking into what's wrong there.

**Comment by ivg** [comment]
`Bitvector.enum_chars` is not buggy, this is a pretty printing in `camlp4`, see ocaml/camlp4#101.

**Comment by maurer** [comment]
Fixed in 0d036379e05ae268c9417e879b8a66fcd907c7f5 (problem was forgetting to call `Int_val` on each char), good catch with the pretty printer.
